### ISSUE TITLE
Version Conflict error

### ISSUE THREAD

**Issue by Rumi4** [Yale-LILY/SummEval#10]
In setup.py, it says spacy 2.2.0 is required. But I get version conflict when I use the given version of spacy.
Here it is:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (spacy 2.2.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('spacy>=2.2.2'), {'en-core-web-sm'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/calc-scores", line 33, in <module>
    sys.exit(load_entry_point('summ-eval', 'console_scripts', 'calc-scores')())
  File "/usr/local/bin/calc-scores", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/SummEval/evaluation/summ_eval/calc_scores.py", line 10, in <module>
    import spacy
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 12, in <module>
    from .cli.info import info as cli_info
  File "/usr/local/lib/python3.6/dist-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/spacy/cli/download.py", line 9, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (spacy 2.2.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('spacy>=2.2.2'), {'en-core-web-sm'})

Please help asap.

**Comment by Alex-Fabbri** [comment]
I tried a fresh install and didn't encounter that error, but you can just install the version from the error message: pip install spacy==2.2.2. 
Please re-open if you have any other questions!

**Comment by Rumi4** [comment]
I installed spacy 2.2.2 but it again returns the error:

File "/usr/local/bin/calc-scores", line 33, in <module>
    sys.exit(load_entry_point('summ-eval', 'console_scripts', 'calc-scores')())
  File "/content/SummEval/evaluation/summ_eval/calc_scores.py", line 28, in cli_main
    gin.parse_config_file(args.config_file)
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1764, in parse_config_file
    includes, imports = parse_config(f, skip_unknown=skip_unknown)
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1678, in parse_config
    __import__(statement.module)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 58, in try_with_location
    augment_exception_message_and_reraise(exception, _format_location(location))
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.6/dist-packages/gin/utils.py", line 56, in try_with_location
    yield
  File "/usr/local/lib/python3.6/dist-packages/gin/config.py", line 1678, in parse_config
    __import__(statement.module)
  File "/content/SummEval/evaluation/summ_eval/bert_score_metric.py", line 2, in <module>
    import bert_score
  File "/usr/local/lib/python3.6/dist-packages/bert_score/__init__.py", line 2, in <module>
    from .score import *
  File "/usr/local/lib/python3.6/dist-packages/bert_score/score.py", line 12, in <module>
    from transformers import AutoTokenizer
  File "/usr/local/lib/python3.6/dist-packages/transformers/__init__.py", line 34, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.6/dist-packages/transformers/dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version_core
  File "/usr/local/lib/python3.6/dist-packages/transformers/utils/versions.py", line 25, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'spacy==2.2.0' distribution was not found and is required by summ-eval
  In file "/content/SummEval/evaluation/examples/basic.config", line 19
    import summ_eval.bert_score_metric

could you please provide a requirements file depicting proper versions required to run the model.
Thanks.

**Comment by Rumi4** [comment]
and when i install 2.2.0 it gives the following error:
ERROR: en-core-web-sm 2.2.5 has requirement spacy>=2.2.2, but you'll have spacy 2.2.0 which is incompatible.

**Comment by Alex-Fabbri** [comment]
When installing 'spacy==2.2.2' change the 'spacy==2.2.0' line in setup.py to reflect this spacy version. You can keep en_core_web_sm-2.2.0 (from the above error it looks like you changed it from the setup.py specification).
