### ISSUE TITLE
Error with ROUGE

### ISSUE THREAD

**Issue by PierreColombo** [Yale-LILY/SummEval#12]
Hello,
Thanks a lot for your work, i find it very usefull .
The line 11 in rouge_metric.py 'ROUGE_HOME = os.environ['ROUGE_HOME']'
Trigger an error 👍 
Traceback (most recent call last):
  File "/Users/colombopierre/Desktop/info_scores_lm/main.py", line 11, in <module>
    from metric import *
  File "/Users/colombopierre/Desktop/info_scores_lm/metric.py", line 4, in <module>
    from summ_eval.rouge_metric import RougeMetric
  File "/Users/colombopierre/Desktop/SummEval/evaluation/summ_eval/rouge_metric.py", line 11, in <module>
    ROUGE_HOME = os.environ['ROUGE_HOME']
  File "/opt/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'ROUGE_HOME'

How should we set this variable ?
Kindest regards,

**Comment by Alex-Fabbri** [comment]
Please run [setup_finalize.py](https://github.com/Yale-LILY/SummEval/blob/master/evaluation/setup_finalize.py), type yes to the prompt "Setup ROUGE?" and then export the path which appears.
