### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by darioTecchia** [Yale-LILY/SummEval#28]
Hi to all, I', trying to install the package from pip3. But I'm getting the following error:
```
$ pip3 install summ-eval
```
```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting summ-eval
  Using cached summ_eval-0.80-py3-none-any.whl (111 kB)
Requirement already satisfied: bert-score in /usr/local/lib/python3.9/site-packages (from summ-eval) (0.3.10)
Requirement already satisfied: click in /usr/local/lib/python3.9/site-packages (from summ-eval) (8.0.3)
Collecting sacrebleu
  Using cached sacrebleu-2.0.0-py3-none-any.whl (90 kB)
Requirement already satisfied: spacy>=2.2.0 in /usr/local/lib/python3.9/site-packages (from summ-eval) (3.2.0)
Collecting pytorch-pretrained-bert
  Using cached pytorch_pretrained_bert-0.6.2-py3-none-any.whl (123 kB)
Requirement already satisfied: stanza in /usr/local/lib/python3.9/site-packages (from summ-eval) (1.3.0)
Collecting blanc
  Using cached blanc-0.2.2-py3-none-any.whl (20 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.9/site-packages (from summ-eval) (2.6.3)
Collecting psutil
  Using cached psutil-5.8.0-cp39-cp39-macosx_10_9_x86_64.whl (236 kB)
Collecting scikit-learn==0.21.3
  Using cached scikit-learn-0.21.3.tar.gz (12.2 MB)
  Preparing metadata (setup.py) ... done
Collecting moverscore
  Using cached moverscore-1.0.3-py3-none-any.whl
Collecting gin-config
  Using cached gin_config-0.5.0-py3-none-any.whl (61 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/site-packages (from summ-eval) (1.7.1)
Collecting pyemd==0.5.1
  Using cached pyemd-0.5.1-cp39-cp39-macosx_11_0_x86_64.whl
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (from summ-eval) (1.16.0)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.9/site-packages (from summ-eval) (0.0.46)
Requirement already satisfied: transformers>=2.2.0 in /usr/local/lib/python3.9/site-packages (from summ-eval) (4.12.3)
Requirement already satisfied: nltk in /usr/local/lib/python3.9/site-packages (from summ-eval) (3.6.5)
Requirement already satisfied: wmd in /usr/local/lib/python3.9/site-packages (from summ-eval) (1.3.2)
Requirement already satisfied: numpy<2.0.0,>=1.9.0 in /usr/local/lib/python3.9/site-packages (from pyemd==0.5.1->summ-eval) (1.21.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.9/site-packages (from scikit-learn==0.21.3->summ-eval) (1.1.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (1.0.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (2.26.0)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (0.7.5)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (0.4.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (3.3.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (3.0.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (21.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (1.8.2)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (1.0.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.8 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (3.0.8)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (2.4.2)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (0.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (3.0.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (2.0.6)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (4.62.3)
Requirement already satisfied: thinc<8.1.0,>=8.0.12 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (8.0.13)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (59.0.1)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (2.0.6)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /usr/local/lib/python3.9/site-packages (from spacy>=2.2.0->summ-eval) (0.8.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/site-packages (from transformers>=2.2.0->summ-eval) (2021.11.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/site-packages (from transformers>=2.2.0->summ-eval) (3.3.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/site-packages (from transformers>=2.2.0->summ-eval) (6.0)
Requirement already satisfied: tokenizers<0.11,>=0.10.1 in /usr/local/lib/python3.9/site-packages (from transformers>=2.2.0->summ-eval) (0.10.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /usr/local/lib/python3.9/site-packages (from transformers>=2.2.0->summ-eval) (0.1.2)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.9/site-packages (from bert-score->summ-eval) (1.3.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/site-packages (from bert-score->summ-eval) (3.4.3)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.9/site-packages (from bert-score->summ-eval) (1.10.0)
Requirement already satisfied: portalocker in /usr/local/lib/python3.9/site-packages (from moverscore->summ-eval) (2.3.2)
Requirement already satisfied: typing in /usr/local/lib/python3.9/site-packages (from moverscore->summ-eval) (3.7.4.3)
Requirement already satisfied: boto3 in /usr/local/lib/python3.9/site-packages (from pytorch-pretrained-bert->summ-eval) (1.20.18)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.9/site-packages (from sacrebleu->summ-eval) (0.8.9)
Requirement already satisfied: colorama in /usr/local/lib/python3.9/site-packages (from sacrebleu->summ-eval) (0.4.4)
Requirement already satisfied: protobuf in /usr/local/lib/python3.9/site-packages (from stanza->summ-eval) (3.19.1)
Requirement already satisfied: emoji in /usr/local/lib/python3.9/site-packages (from stanza->summ-eval) (1.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers>=2.2.0->summ-eval) (3.10.0.2)
Requirement already satisfied: pyparsing<3,>=2.0.2 in /usr/local/lib/python3.9/site-packages (from packaging>=20.0->spacy>=2.2.0->summ-eval) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/site-packages (from pandas>=1.0.1->bert-score->summ-eval) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/site-packages (from pandas>=1.0.1->bert-score->summ-eval) (2021.3)
Requirement already satisfied: smart-open<6.0.0,>=5.0.0 in /usr/local/lib/python3.9/site-packages (from pathy>=0.3.5->spacy>=2.2.0->summ-eval) (5.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.0->summ-eval) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.0->summ-eval) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.0->summ-eval) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.0->summ-eval) (2.0.7)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.9/site-packages (from boto3->pytorch-pretrained-bert->summ-eval) (0.10.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /usr/local/lib/python3.9/site-packages (from boto3->pytorch-pretrained-bert->summ-eval) (0.5.0)
Requirement already satisfied: botocore<1.24.0,>=1.23.18 in /usr/local/lib/python3.9/site-packages (from boto3->pytorch-pretrained-bert->summ-eval) (1.23.18)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/site-packages (from jinja2->spacy>=2.2.0->summ-eval) (2.0.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/site-packages (from matplotlib->bert-score->summ-eval) (8.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/site-packages (from matplotlib->bert-score->summ-eval) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/site-packages (from matplotlib->bert-score->summ-eval) (0.11.0)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py'"'"'; __file__='"'"'/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-wheel-3yq4iml1
       cwd: /private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/
  Complete output (50 lines):
  Partial import of sklearn during the build process.
  C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall
  
  compile options: '-c'
  extra options: '-fopenmp'
  clang: test_openmp.c
  clang: error: unsupported option '-fopenmp'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py", line 290, in <module>
      setup_package()
    File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py", line 286, in setup_package
      setup(**metadata)
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py", line 174, in configuration
      config.add_subpackage('sklearn')
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1016, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 982, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sklearn/setup.py", line 76, in configuration
      maybe_cythonize_extensions(top_path, config)
    File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/sklearn/_build_utils/__init__.py", line 42, in maybe_cythonize_extensions
      with_openmp = check_openmp_support()
    File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/sklearn/_build_utils/openmp_helpers.py", line 140, in check_openmp_support
      raise CompileError(err_message)
  distutils.errors.CompileError:
                      ***
  
  It seems that scikit-learn cannot be built with OpenMP support.
  
  - Make sure you have followed the installation instructions:
  
      https://scikit-learn.org/dev/developers/advanced_installation.html
  
  - If your compiler supports OpenMP but the build still fails, please
    submit a bug report at:
  
      https://github.com/scikit-learn/scikit-learn/issues
  
  - If you want to build scikit-learn without OpenMP support, you can set
    the environment variable SKLEARN_NO_OPENMP and rerun the build
    command. Note however that some estimators will run in sequential
    mode and their `n_jobs` parameter will have no effect anymore.
  
                      ***
  
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
Installing collected packages: scikit-learn, sacrebleu, pytorch-pretrained-bert, pyemd, psutil, moverscore, gin-config, blanc, summ-eval
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py'"'"'; __file__='"'"'/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-record-rq1ujac5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/scikit-learn
         cwd: /private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/
    Complete output (50 lines):
    Partial import of sklearn during the build process.
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall
    
    compile options: '-c'
    extra options: '-fopenmp'
    clang: test_openmp.c
    clang: error: unsupported option '-fopenmp'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py", line 290, in <module>
        setup_package()
      File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py", line 286, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 1016, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 982, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/usr/local/lib/python3.9/site-packages/numpy/distutils/misc_util.py", line 924, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 76, in configuration
        maybe_cythonize_extensions(top_path, config)
      File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/sklearn/_build_utils/__init__.py", line 42, in maybe_cythonize_extensions
        with_openmp = check_openmp_support()
      File "/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/sklearn/_build_utils/openmp_helpers.py", line 140, in check_openmp_support
        raise CompileError(err_message)
    distutils.errors.CompileError:
                        ***
    
    It seems that scikit-learn cannot be built with OpenMP support.
    
    - Make sure you have followed the installation instructions:
    
        https://scikit-learn.org/dev/developers/advanced_installation.html
    
    - If your compiler supports OpenMP but the build still fails, please
      submit a bug report at:
    
        https://github.com/scikit-learn/scikit-learn/issues
    
    - If you want to build scikit-learn without OpenMP support, you can set
      the environment variable SKLEARN_NO_OPENMP and rerun the build
      command. Note however that some estimators will run in sequential
      mode and their `n_jobs` parameter will have no effect anymore.
    
                        ***
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py'"'"'; __file__='"'"'/private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-install-buu7jz_9/scikit-learn_6919c14a0bd74b4588354d6c55f9ba61/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dl/8zw1stks57g6d4q039zrlpm80000gn/T/pip-record-rq1ujac5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/scikit-learn Check the logs for full command output.
```

**Comment by darioTecchia** [comment]
```
$ pip3 -V
pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
$ python3 -V
Python 3.9.9
```

**Comment by paluchasz** [comment]
I recall having a similar issue with python 3.7.11 and I think just upgrading pip worked in the end. Though looks like you have the latest pip.
