### ISSUE TITLE
error while running setup on windows

### ISSUE THREAD

**Issue by shankyemcee** [Yale-LILY/SummEval#34]
After running these lines:

git clone https://github.com/Yale-LILY/SummEval.git
cd SummEval/evaluation
pip install -e .

Im getting this error. i think theres a problem in the setup script.

Obtaining file:///C:/Users/Dell%20G7%20User%202/Documents/PROJECTS/envs/summeval_env/SummEval/evaluation
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
      Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
      To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
      Collecting cython
        Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
      Installing collected packages: cython
      Successfully installed cython-0.29.28
      running egg_info
      creating C:\Users\DELLG7~1\AppData\Local\Temp\pip-pip-egg-info-drb1ur0s\summ_eval.egg-info
      writing C:\Users\DELLG7~1\AppData\Local\Temp\pip-pip-egg-info-drb1ur0s\summ_eval.egg-info\PKG-INFO
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Dell G7 User 2\Documents\PROJECTS\envs\summeval_env\SummEval\evaluation\setup.py", line 48, in <module>
          'calc-scores = summ_eval.calc_scores:cli_main',
        File "c:\users\dell g7 user 2\documents\projects\envs\summeval_env\lib\site-packages\setuptools\__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Dell G7 User 2\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Dell G7 User 2\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Dell G7 User 2\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\dell g7 user 2\documents\projects\envs\summeval_env\lib\site-packages\setuptools\command\egg_info.py", line 289, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "c:\users\dell g7 user 2\documents\projects\envs\summeval_env\lib\site-packages\setuptools\command\egg_info.py", line 621, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "C:\Users\Dell G7 User 2\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 1117, in write_pkg_info
          self.write_pkg_file(pkg_info)
        File "c:\users\dell g7 user 2\documents\projects\envs\summeval_env\lib\site-packages\setuptools\dist.py", line 166, in write_pkg_file
          long_desc = rfc822_escape(self.get_long_description())
        File "C:\Users\Dell G7 User 2\AppData\Local\Programs\Python\Python37\lib\distutils\util.py", line 464, in rfc822_escape
          lines = header.split('\n')
      TypeError: a bytes-like object is required, not 'str'
      Error in atexit._run_exitfuncs:
      Traceback (most recent call last):
        File "c:\users\dell g7 user 2\documents\projects\envs\summeval_env\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 59, in closed
          return stream.closed
      ValueError: underlying buffer has been detached
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Alex-Fabbri** [comment]
I believe the error should be fixed now. Please reopen the issue if it persists!
